# Generated by Django 3.2 on 2021-04-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_data', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.video')),
                ('text_data', models.FileField(upload_to='text/')),
            ],
        ),
    ]
